// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'en' | 'vi';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  contactTable: {
    /**
     * C​o​n​t​a​c​t
     */
    contact: string;
    /**
     * T​e​l
     */
    tel: string;
    /**
     * E​m​a​i​l
     */
    email: string;
    /**
     * A​d​d​r​e​s​s
     */
    address: string;
  };
  postCard: {
    /**
     * R​e​a​d​ ​m​o​r​e
     */
    readMore: string;
  };
};

export type TranslationFunctions = {
  contactTable: {
    /**
     * Contact
     */
    contact: () => LocalizedString;
    /**
     * Tel
     */
    tel: () => LocalizedString;
    /**
     * Email
     */
    email: () => LocalizedString;
    /**
     * Address
     */
    address: () => LocalizedString;
  };
  postCard: {
    /**
     * Read more
     */
    readMore: () => LocalizedString;
  };
};

export type Formatters = {};
